### ISSUE TITLE
Broken dataset.metadata for 4TU Datasets

### ISSUE THREAD

**Issue by manuGil** [ITC-CRIB/fairly#12]
Calling the `fairly.dataset.metadata` returns  **403 HTTP Error**, when remote dataset is created for 4TU.ReseachData. Is this something related to changing the platform (removing figshare)?

Do we need a token to access the Figshare and Zenodo API in any case? It seems that way.

Examples:

```python
import fairly

# using a direct method
dataset = fairly.dataset("https://doi.org/10.4121/19519618.v1")
#show metadata
dataset.metadata

# ===============
# using a client

fourtu = fairly.client("4tu")
dataset = fourtu.get_dataset("https://data.4tu.nl/articles/dataset/EDoM_measurement_campaign_full_data_from_the_lower_Ems_River/20308263")

dataset.metadata
```
Raise the following error:

```python
  File "fairly/src/fairly/client/figshare.py", line 231, in _get_licenses
    items, _ = self._request(endpoint)
  File "fairly/src/fairly/client/__init__.py", line 301, in _request
    response.raise_for_status()
  File "/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.figshare.com/v2/account/licenses
```

**Comment by manuGil** [comment]
Do these operations require token authorization? The Zonodo API report the same HTTP error if no token is set

**Comment by girgink** [comment]
403 error is due to invalid access token. I think the one in use was expired. I had the same issue and it worked correctly after I re-generated the token. fairly tries to standardize the license return by the metadata endpoint and for that purposes retrieves the list of licenses. Private license endpoint returns both the private and public licenses; hence it is preferred if access token is defined. However, this results in error if the token is invalid.

I will add a try-catch block and fallback to the public license endpoint it case of error.

**Comment by manuGil** [comment]
@girgink **From which file is this token read?** The one in `.fairly/repositories.json`?
```json
{
	"figshare": {
		"token": "88888888888"
	}
}
```

**Comment by girgink** [comment]
@manuGil, yes, it is read from `~/.fairly/repositories.json`

**Comment by manuGil** [comment]
@girgink  I got this working, but I had to initiate a client by passing the token. It seems my `.fairly/repositories.json` file is not been read, at least not in the set-up, I have for integrating it with the extension. However, I think the following point is more important. In my testing, cloning a dataset fails with the error above whenever the client cannot authenticate. **Is this correct?**  However, I don't think we should enforce authentication when pulling public datasets, unless for the case of owned datasets. Any thoughts on that?

**Comment by jurra** [comment]
@manuGil could you try one of my latest branches and see if that works? `feature/fairly_cli` or  `bugfix/#15_Unit_testing_overwriting_config_file`.

**Comment by girgink** [comment]
@jurra @manuGil This required modification of license retrieval logic as we discussed recently. I have implemented it, so it is working as expected now. I have also corrected `get_categories` method, which has a similar logic with `get_licenses`.
