### ISSUE TITLE
Dependency packages should not have fixed versions

### ISSUE THREAD

**Issue by girgink** [ITC-CRIB/fairly#13]
@jurra Can you please correct the development dependencies in the `pyproject.toml` file? We shouldn't use fixed versions, this is bad practice for shared environments. Please remove the versions if we don't need specific versions, or use minimum (`>=`) condition.

**Comment by jurra** [comment]
Hi @girgink I have put the package dependencies all loose. Nevertheless for the development environment I do think they should be strictly defined and match to only one version. This is important for debugging and reproducing errors. Please let me know what you think if you agree or if I am missing another detail.

**Comment by girgink** [comment]
I think we have a quite generic development environment, which in fact only differs in packages required for unit testing. I don't think fixing the versions of unit testing packages is necessary. They are really core packages, it is a good practice to have the latest versions.
