### ISSUE TITLE
Unit testing: repository configuration should not be stored in config.json

### ISSUE THREAD

**Issue by girgink** [ITC-CRIB/fairly#16]
Unit testing uses `~/.fairly/config.json` to store repository-specific configuration (e.g. access token). This is not correct. `config.json` is not used to store repository configuration, it is for fairly package configuration parameters, e.g. ORCID application token. `~/.fairly/repositories.json` should be used instead.

**Comment by jurra** [comment]
I am a bit confused with the differences maybe we should also clarify this. I used the config to store now the access token. So is this correct or not? To be honest the configuration workflow has been quite confusing to me, I just assumed certain things based on reading the code and trying to test it.

**Comment by girgink** [comment]
I understand the confusion. As discussed, I have simplified the configuration by merging `repository.json` and `config.json` into a single configuration, which is named `config.json`.
