### ISSUE TITLE
Protect main branch from direct push and implement pull request with tests

### ISSUE THREAD

**Issue by jurra** [ITC-CRIB/fairly#18]
Hi @girgink I saw there was a direct push to the branch and now tests are failing. I think is wise to avoid direct pushes to the main branch and push always to a separate branch to check if tests are passing.

**Comment by jurra** [comment]
A simple solution for now can be to have a develop branch where we can push things faster if you like and keep the main branch stable, only modifiable via pull requests.

**Comment by girgink** [comment]
Main branch protection is enabled. I didn't enable inclusion of the administrators for the time being not to slow down development. Once we publish the first version we can also enable that.
