### ISSUE TITLE
Invalid URL for new 4TU.ReasearchData endpoints

### ISSUE THREAD

**Issue by manuGil** [ITC-CRIB/fairly#26]
The change in platform in this repository means that the current version of the package doesn't accept the new endpoints. This is evident when using URLs, but using DOI seems to work.

The previous endpoint had this pattern: 
`https://data.4tu.nl/articles/dataset/<title>/<id>`

New endpoints have this pattern:
`https://data.4tu.nl/datasets/<uuid>`

**Comment by manuGil** [comment]
Previous tokens to 4TU are no longe valid

**Comment by girgink** [comment]
I think we should cover such issues while working on a Djehuty client, as there are more to consider. I close this one for the time being.
