### ISSUE TITLE
Review for workshop session

### ISSUE THREAD

**Issue by jurra** [ITC-CRIB/fairly#7]
Hi Serkan and Manuel, I am reviewing the documentation and will write down the things I have seen here.

I went through all the notebooks and tested them, nice that you have setup these examples Manuel!

Here are some observations:
1. Why is the docs in the jupyFAIR repo instead of the fairly package repo? I would have added the docs as a subdirectory in the fairly package itself.
- I would move the notebooks to an examples folder in the package repository and remove references to the cli and extension for the time being. (Unless you want to show a roadmap to the audience, where only a small portion is implemented)
- All the example scripts/notebooks should be contained in my opinion right in te source code, even adding to the gitignore the files and folders to be ignored when they are running, in case someone uses it from the source code.
- Focus only on the documentation of the package this much simpler documentation maintainance that a read the docs website for the time being when we are still in early stage. Updating the documentation should be simple (for example adding a simple example script and updating some markdown file, and that is enough, vs updating a website already, to me a couple of links in the main readme to the example notebooks is good enough for the level of solution we have.)
2. The idea of using the client without an api token for some things and not for others and the whole configuration approach feels a bit confusing.
3. In the documentation section 2. Retrieve datasets, I would name it Retrieve user (or account) datasets.

**Comment by manuGil** [comment]
Thanks for your comments @jurra. You're having the documentation and the code together would make things simpler. We should do that in the future.
